eyacdotes/Capstone-Place_IT

- app/Http/Controllers/BusinessOwnerController.php
- package-lock.json
- resources/views/dashboard/business.blade.php
- resources/views/dashboard/space.blade.php
space owner table responsive and no records found if no date in searched date in space owner
> Responsiveness and Error handling

- app/Http/Controllers/CreateListingController.php
- app/Models/Listing.php
- database/migrations/2024_08_16_115336_create_listing_table.php
> handling image upload and image table added in database

- resources/views/auth/business-register.blade.php
- resources/views/auth/login.blade.php
- resources/views/auth/space-register.blade.php
- resources/views/components/primary-button.blade.php
- resources/views/layouts/app.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/layouts/guest.blade.php
- resources/views/layouts/space-navigation.blade.php
- resources/views/welcome.blade.php
UI (landing page, login / register) and responsiveness to all forms (login / register)
> Plss ko approve sa UI

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/CreateListingController.php
- app/Http/Controllers/NotificationController.php
- app/Http/Controllers/SpaceOwnerController.php
- app/Models/Notification.php
- app/Notifications/p_notif.php
- database/migrations/2024_09_23_093923_create_notifications_table.php
- resources/views/dashboard/space.blade.php
- resources/views/layouts/admin-navigation.blade.php
- resources/views/layouts/space-navigation.blade.php
- resources/views/space_owner/newspaces.blade.php
- routes/web.php
enhanced SO to ADMIN (vice versa) notifications with proper labeling of listing with changes in migrations notification table and Delete Listing already working
> Notifications and Delete Lising

- package-lock.json
- resources/views/auth/business-register.blade.php
- resources/views/auth/space-register.blade.php
> simple changes to register

- resources/views/layouts/guest.blade.php
- resources/views/welcome.blade.php
> margin top for reg and login

- resources/views/emails/verify_email_otp.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/layouts/guest.blade.php
- resources/views/welcome.blade.php
improved ui and load handling in send otp form using ajax jquery
> improved ui and load handling in send otp form using ajax jquery

- app/Http/Controllers/BusinessOwnerController.php
- resources/views/dashboard/space.blade.php
- resources/views/place/detail.blade.php
- resources/views/place/showByLocation.blade.php
- resources/views/welcome-modal.blade.php
- resources/views/welcome.blade.php
> complete ads dashboard

- resources/views/components/nav-link.blade.php
- resources/views/dashboard/space.blade.php
- resources/views/layouts/space-navigation.blade.php
removed slideshow for ads and the fonts back to minimalist
> removed slideshow for ads and the fonts back to minimalist

- resources/views/emails/verify_email_otp.blade.php
> IMPROVED UI OTP

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/BusinessOwnerController.php
- app/Http/Controllers/NegotiationController.php
- app/Models/Payment.php
- app/Models/RentalAgreement.php
- database/migrations/2024_10_18_182909_add_is_paid_to_rental_agreements_table.php
- resources/views/admin/payment.blade.php
- resources/views/business_owner/feedback.blade.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/dashboard/space.blade.php
- resources/views/space_owner/messagedetail.blade.php
- routes/web.php
> improved transactions

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NegotiationController.php
- app/Models/MeetupProof.php
- app/Models/RentalAgreement.php
- database/migrations/2024_10_19_114359_create_meetup_proofs_table.php
- resources/views/admin/payment.blade.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/space_owner/messagedetail.blade.php
- routes/web.php
new table meetup_proof, notifications done, send proof image modal, no function
> new table meetup_proof, notifications done, send proof image modal, no function

- app/Http/Controllers/NegotiationController.php
- app/Http/Controllers/SpaceOwnerController.php
- app/Models/Listing.php
- app/Models/Negotiation.php
- app/Models/Payment.php
- resources/views/admin/listingmanagement.blade.php
- resources/views/admin/payment.blade.php
- resources/views/dashboard/space.blade.php
- resources/views/place/detail.blade.php
- resources/views/space_owner/messagedetail.blade.php
- resources/views/welcome-modal.blade.php
- routes/web.php
sent proof meetup, and admin can view, occupied space
> sent proof meetup, and admin can view, occupied space

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/BusinessOwnerController.php
- app/Http/Controllers/NegotiationController.php
- app/Models/Payment.php
- resources/views/admin/payment.blade.php
- resources/views/place/detail.blade.php
- resources/views/space_owner/messagedetail.blade.php
- resources/views/welcome-modal.blade.php
fixed transactions, other modals no flex
> fixed transactions, other modals no flex

- resources/views/components/application-logo.blade.php
- resources/views/welcome.blade.php
> Welcome Blade Carousel

- resources/views/business_owner/bookinghistory.blade.php
- resources/views/business_owner/view_feedback.blade.php
BO booking history and feedback table
> BO booking history and feedback table

- app/Http/Controllers/NotificationController.php
- resources/views/layouts/admin-navigation.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/layouts/space-navigation.blade.php
Notifications for 3 users (admin, so, bo) bg gray in unread and new notif for maintenance implemented
> Notifications for 3 users (admin, so, bo) fixed

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NegotiationController.php
- app/Http/Controllers/NotificationController.php
- app/Mail/FollowUp.php
- resources/views/business_owner/negotiations.blade.php
- resources/views/emails/follow_up.blade.php
- resources/views/layouts/admin-navigation.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/layouts/space-navigation.blade.php
- resources/views/space_owner/negotiations.blade.php
- routes/web.php
done admin notif selected, chat notifications
> done admin notif selected, chat notifications

- resources/views/business_owner/bookinghistory.blade.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/space_owner/messagedetail.blade.php
reponsiveness of message detail both users and booking history of BO
> UI reponsiveness

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NotificationController.php
- resources/views/business_owner/view_feedback.blade.php
- resources/views/dashboard/business.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/space_owner/payment_details.blade.php
> small changes

- resources/views/business_owner/messagedetail.blade.php
> update offer back

- app/Http/Controllers/NotificationController.php
- resources/views/layouts/admin-navigation.blade.php
- resources/views/space_owner/payment_details.blade.php
> notifacation fixed

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NegotiationController.php
- app/Mail/RentalAgreementMailable.php
- app/Models/RentalAgreement.php
- composer.json
- composer.lock
- resources/views/admin/listingmanagement.blade.php
- resources/views/admin/negotiations.blade.php
- resources/views/admin/payment_report.blade.php
- resources/views/admin/reports.blade.php
- resources/views/admin/reviews.blade.php
- resources/views/admin/system_feedback.blade.php
- resources/views/admin/transaction.blade.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/emails/receipts.blade.php
- resources/views/emails/rental_agreements.blade.php
- resources/views/layouts/admin-navigation.blade.php
- resources/views/space_owner/payment_details.blade.php
- routes/web.php
rental agree email, print receipt, and reports
> rental agree email, print receipt, and reports

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NegotiationController.php
- resources/views/admin/reports.blade.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/emails/rental_agreements.blade.php
- resources/views/place/detail.blade.php
- resources/views/space_owner/payment_details.blade.php
> final period

- app/Models/Negotiation.php
- app/Models/RentalAgreement.php
> new models

- app/Http/Controllers/BusinessOwnerController.php
- app/Http/Controllers/SpaceOwnerController.php
- resources/views/business_owner/messagedetail.blade.php
- resources/views/business_owner/reports.blade.php
- resources/views/dashboard/space.blade.php
- resources/views/layouts/business-navigation.blade.php
- resources/views/layouts/space-navigation.blade.php
- resources/views/space_owner/messagedetail.blade.php
- resources/views/space_owner/negotiations.blade.php
- resources/views/space_owner/payment_details.blade.php
- resources/views/space_owner/reports.blade.php
- routes/web.php
> reports revisions
